# Generated by Django 5.2 on 2025-04-29 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_match_id', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True)),
                ('match_timestamp', models.DateTimeField(db_index=True, help_text='Дата и время начала игры')),
                ('duration_secons', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-match_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
