# Generated by Django 5.2 on 2025-04-30 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerMatchStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('won_match', models.BooleanField(default=False, help_text='Выиграл ли игрок этот матч?')),
                ('kills', models.PositiveIntegerField(default=0)),
                ('deaths', models.PositiveIntegerField(default=0)),
                ('assists', models.PositiveIntegerField(default=0)),
                ('skills_used', models.PositiveIntegerField(default=0, help_text='Общее кол-во примененных умений (кроме ультимейтов)')),
                ('ultimates_used', models.PositiveIntegerField(default=0, help_text='Кол-во примененных ультимейтов')),
                ('time_alive_seconds', models.PositiveIntegerField(default=0, help_text='Общее время жизни в матче в секундах')),
                ('bomb_plants', models.PositiveIntegerField(default=0, help_text='Сколько раз установил бомбу')),
                ('bomb_defuses', models.PositiveIntegerField(default=0, help_text='Сколько раз обезвредил бомбу')),
                ('headshots', models.PositiveIntegerField(default=0)),
                ('bodyshots', models.PositiveIntegerField(default=0)),
                ('legshots', models.PositiveIntegerField(default=0)),
                ('total_shots_hit', models.PositiveIntegerField(default=0, help_text='Всего выстрелов попало')),
                ('total_shots_fired', models.PositiveIntegerField(default=0, help_text='Всего выстрелов сделано')),
                ('primary_weapon_used', models.CharField(blank=True, help_text='Основное/самое результативное оружие', max_length=100)),
                ('armor_lvl1_purchases', models.PositiveIntegerField(default=0, help_text='Сколько раз купил броню 1 ур.')),
                ('armor_lvl2_purchases', models.PositiveIntegerField(default=0, help_text='Сколько раз купил броню 2 ур.')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_stats', to='stats_api.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_stats', to='stats_api.player')),
            ],
            options={
                'verbose_name': 'Статистика игрока за матч',
                'verbose_name_plural': 'Статистика игроков за матчи',
                'ordering': ['-match__match_timestamp'],
                'unique_together': {('player', 'match')},
            },
        ),
    ]
