# Generated by Django 5.2 on 2025-04-30 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats_api', '0002_playermatchstats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playermatchstats',
            old_name='total_shots_hit',
            new_name='total_shots_hitted',
        ),
    ]
