# Generated by Django 5.2 on 2025-05-01 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats_api', '0004_rename_duration_secons_match_duration_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='game_mode',
            field=models.CharField(blank=True, help_text='Режим игры', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='is_ranked',
            field=models.CharField(blank=True, help_text='Является ли матч ранговым', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='map_name',
            field=models.CharField(blank=True, help_text='Название карты', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='queue_id',
            field=models.CharField(blank=True, help_text='ID очереди (competitive, unrated)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_timestamp',
            field=models.DateTimeField(db_index=True, help_text='Дата и время начала игры', null=True),
        ),
    ]
