# Generated by Django 5.2 on 2025-05-02 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats_api', '0005_match_game_mode_match_is_ranked_match_map_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['username'], 'verbose_name': 'Игрок', 'verbose_name_plural': 'Игроки'},
        ),
        migrations.RemoveField(
            model_name='match',
            name='map_name',
        ),
        migrations.AddField(
            model_name='player',
            name='puuid',
            field=models.CharField(blank=True, db_index=True, help_text='Уникальный идентификатор игрока', max_length=80, null=True, unique=True, verbose_name='PUUID'),
        ),
        migrations.AlterField(
            model_name='player',
            name='username',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
