# Generated by Django 5.2 on 2025-05-10 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats_api', '0007_match_map_name_alter_match_is_ranked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='queue_id',
        ),
        migrations.AddField(
            model_name='match',
            name='rounds_played',
            field=models.PositiveIntegerField(blank=True, help_text='Количество сыгранных раундов', null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='duration_seconds',
            field=models.PositiveIntegerField(blank=True, help_text='Продолжительность игры (в секундах)', null=True),
        ),
    ]
