# Generated by Django 5.2 on 2025-05-10 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats_api', '0008_remove_match_queue_id_match_rounds_played_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='rank',
            field=models.CharField(blank=True, db_index=True, help_text='Ранг игрока', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='username',
            field=models.CharField(blank=True, db_index=True, help_text='Никнейм игрока', max_length=100, null=True),
        ),
    ]
