# Generated by Django 5.2 on 2025-05-11 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats_api', '0009_player_rank_alter_player_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='playermatchstats',
            name='headshot_rate',
            field=models.FloatField(default=0.0, help_text='Процент выстрелов в голову от общих попаданий'),
        ),
        migrations.AddField(
            model_name='playermatchstats',
            name='kda',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='playermatchstats',
            name='total_shots_hitted',
            field=models.PositiveIntegerField(default=0, help_text='Всего выстрелов попали'),
        ),
    ]
