# Generated by Django 5.2 on 2025-05-13 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats_api', '0010_playermatchstats_headshot_rate_playermatchstats_kda_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='game_name',
            field=models.CharField(choices=[('valorant', 'Valorant'), ('pubg', 'PUBG')], default='valorant', help_text='Название игры', max_length=20),
        ),
        migrations.AddField(
            model_name='player',
            name='game_name',
            field=models.CharField(choices=[('valorant', 'Valorant'), ('pubg', 'PUBG')], default='valorant', help_text='Название игры', max_length=20),
        ),
        migrations.AddField(
            model_name='playermatchstats',
            name='boosts_used',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Количество использованных усилений', null=True),
        ),
        migrations.AddField(
            model_name='playermatchstats',
            name='dbnos',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Down But Not Out - количество нокаутов', null=True),
        ),
        migrations.AddField(
            model_name='playermatchstats',
            name='game_name',
            field=models.CharField(choices=[('valorant', 'Valorant'), ('pubg', 'PUBG')], default='valorant', help_text='Название игры', max_length=20),
        ),
        migrations.AddField(
            model_name='playermatchstats',
            name='heals_used',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Количество использованных усилений лечений', null=True),
        ),
        migrations.AddField(
            model_name='playermatchstats',
            name='longest_kill_distance',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Самое дальнее убийство', null=True),
        ),
        migrations.AddField(
            model_name='playermatchstats',
            name='revives',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Количество воскрешенных союзников', null=True),
        ),
        migrations.AlterField(
            model_name='playermatchstats',
            name='armor_lvl1_purchases',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Сколько раз купил броню 1 ур.', null=True),
        ),
        migrations.AlterField(
            model_name='playermatchstats',
            name='armor_lvl2_purchases',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Сколько раз купил броню 2 ур.', null=True),
        ),
        migrations.AlterField(
            model_name='playermatchstats',
            name='bodyshots',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='playermatchstats',
            name='bomb_defuses',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Сколько раз обезвредил бомбу', null=True),
        ),
        migrations.AlterField(
            model_name='playermatchstats',
            name='bomb_plants',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Сколько раз установил бомбу', null=True),
        ),
        migrations.AlterField(
            model_name='playermatchstats',
            name='headshots',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='playermatchstats',
            name='legshots',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='playermatchstats',
            name='primary_weapon_used',
            field=models.CharField(blank=True, help_text='Основное/самое результативное оружие', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='playermatchstats',
            name='skills_used',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Общее кол-во примененных умений (кроме ультимейтов)', null=True),
        ),
        migrations.AlterField(
            model_name='playermatchstats',
            name='time_alive_seconds',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Общее время жизни в матче в секундах', null=True),
        ),
        migrations.AlterField(
            model_name='playermatchstats',
            name='total_shots_fired',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Всего выстрелов сделано', null=True),
        ),
        migrations.AlterField(
            model_name='playermatchstats',
            name='total_shots_hitted',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Всего выстрелов попали', null=True),
        ),
        migrations.AlterField(
            model_name='playermatchstats',
            name='ultimates_used',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Кол-во примененных ультимейтов', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='match',
            unique_together={('game_match_id', 'game_name')},
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('puuid', 'game_name')},
        ),
    ]
