# Generated by Django 5.2 on 2025-05-13 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats_api', '0011_match_game_name_player_game_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playermatchstats',
            name='damage_dealt',
            field=models.PositiveIntegerField(default=0.0, help_text='Нанесенный урон'),
        ),
    ]
