# Generated by Django 5.2 on 2025-05-16 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats_api', '0012_playermatchstats_damage_dealt'),
    ]

    operations = [
        migrations.AddField(
            model_name='playermatchstats',
            name='unique_abilities_used',
            field=models.PositiveIntegerField(default=0, help_text='Использованные уникальные возможности игры'),
        ),
    ]
